### ISSUE TITLE
Cannot run sample

### ISSUE THREAD

**Issue by nojaf** [VandenkerckhoveJesse/Axxes.SkiSimulation.Templates#2]
Fresh clone of repository:

![image](https://user-images.githubusercontent.com/2621499/78156748-7dc44d80-743f-11ea-80e0-9b22bc91ee01.png)

**Comment by lukaspetit** [comment]
Main class was internal, now public

**Comment by nojaf** [comment]
@VandenkerckhoveJesse @lukaspetit I've synced my fork and tried it again.
It works now.
Maybe a general piece of advice: ask the user to try again when you have a fix and let them close the issue. This doesn't always apply but in this case, it seemed more appropriate. 

The docker containers do not shut down automatically once the result is determined.

```
engine_1     | result= '{"Points": [{"X":4,"Y":0},{"X":4,"Y":1},{"X":4,"Y":2},{"X":4,"Y":3}],"Map": [[0,0,0,0,0,0,0,0,0]
,[0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0],[1,1,1,1,1,0,0,0,0],[0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0]
,[0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0],[0,0,0,0,1,1,1,1,1],[0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0]
,[0,0,0,0,0,0,0,0,0],[1,1,1,1,0,0,0,0,0]]}'
algorithm_1  | Unhandled exception. Grpc.Core.RpcException: Status(StatusCode=Cancelled, Detail="")
algorithm_1  |    at Axxes.SkiSimulation.Algorithms.NET.Program.Main(String[] args) in /app/Program.cs:line 29
algorithm_1  |    at Axxes.SkiSimulation.Algorithms.NET.Program.<Main>(String[] args)
axxesskisimulationtemplates_algorithm_1 exited with code 139
```
